razorpay:
  key: rzp_test_6i2006Za1fnyi8
  secret: Bh9WhUaadKNizBX7vQgLZ6tO

spring:
  application:
    name: paymentgateway-management-ms

  data:
    mongodb:
      database: soshealth
      uri: mongodb://soshealth:oUoGMmS5r4gPGltAoiT10bJsCnEsNrTQZZNM4veYjjtVSAsrbmlDXuZTewRdCKreWZdIZ79iglWttqR6gUArMw==@soshealth.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@soshealth@

server:
  http2:
    enabled: true
  port: 9000
